export const sampleColumns = [
  {
    name: "id_pkey",
    required: true,
    label: "Id",
    field: "id_pkey",
    align: "left",
    sortable: true,
  },
  {
    name: "date_iso",
    required: true,
    label: "Date",
    field: "date_iso",
    align: "left",
    sortable: true,
  },
  {
    name: "timezone",
    required: true,
    label: "Timezone",
    field: "timezone",
    align: "left",
    sortable: true,
  },
  {
    name: "latitude",
    required: true,
    label: "Latitude",
    field: "latitude",
    align: "left",
    sortable: true,
  },
  {
    name: "longitude",
    required: true,
    label: "Longitude",
    field: "longitude",
    align: "left",
    sortable: true,
  },
  {
    name: "altitude",
    required: true,
    label: "Altitude",
    field: "altitude",
    align: "left",
    sortable: true,
  },
  {
    name: "velocity",
    required: true,
    label: "Velocity",
    field: "velocity",
    align: "left",
    sortable: true,
  },
];
